nlevels: 5
ratio: 2.0

preprocessing_blur: True
preprocessing_blur_sigma: 2.0

detection_min_dist: 15
detection_threshold: 2.5
detection_blur: 6.0

optical_flow_max_iter: 25
optical_flow_lm_lambda: 0.1