nlevels: 5
ratio: 2.0

preprocessing_blur: True
preprocessing_blur_sigma: 1.5

detection_min_dist: 15
detection_threshold: 2.5
detection_blur: 6.0

optical_flow_max_iter: 20
optical_flow_lm_lambda: 2.0